---
# Ansible script to creste a file on target servers.
#Usage: ansible-playbook -i inventory LiferayDeploymentReport.yml -l <envType>
#Usage: ansible-playbook -i inventory LiferayDeploymentReport.yml -l DEV
## power devops -

- hosts: all
  remote_user: '{{ mi_user }}'

  vars:
    file_contents: "{{lookup('file', 'contents.txt')}}"

  vars_files:
    - ./vars/passwd.yml

  tasks:

  - name: Deployment facts
    debug: msg="list of files are {{ item }}"
    with_items:
      - "{{ file_contents }}"
    run_once: true

  - name: create output file
    file: path={{workspace}}/results.txt state=touch
    register: fileCreate
    delegate_to: localhost
    run_once: true

  - name: Creating file using oracle user
    file: path={{baseDir}}/lifeary.txt state=touch
    when: inventory_hostname in groups['Node1']
    become: yes
    become_user: oracle
    become_method: sudo

  - name: list lifeary cretaed file
    shell: ls -lrt "{{baseDir}}/lifeary.txt"
    when: inventory_hostname in groups['Node1']
    register: resOut


  - name: print created log file result
    shell: echo "Created file info with Timestamp - {{resOut.stdout}}" >> {{workspace}}/results.txt
    when: not(resOut|skipped)
    delegate_to: localhost
